# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cuopt-sh-client
  version: ${{ version }}

source:
  path: ../../..

build:
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cuopt_sh_client

requirements:
  host:
    - pip
    - python =${{ py_version }}
    - setuptools>=61.0.0
  run:
    - msgpack-python =1.1.0
    - python
    - requests

tests:
  - python:
      imports:
        - cuopt_sh_client
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cuopt_self_hosted/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cuopt_self_hosted/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cuopt_self_hosted/pyproject.toml").project.description }}
