name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - changed-files
      - checks
      - conda-cpp-build
      - conda-cpp-tests
      - conda-python-build
      - conda-python-tests
      - docs-build
      - wheel-build-libcuopt
      # - conda-notebook-tests
      - wheel-build-cuopt
      - wheel-tests-cuopt
      - wheel-build-cuopt-server
      - wheel-tests-cuopt-server
      - wheel-build-cuopt-mps-parser
      - wheel-build-cuopt-sh-client
      - test-self-hosted-server
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-25.08
  changed-files:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/changed-files.yaml@branch-25.08
    with:
      files_yaml: |
        test_cpp:
          - '**'
          - '!CONTRIBUTING.md'
          - '!README.md'
          - '!ci/release/update-version-cuopt.sh'
          - '!ci/release/update-version-rapids.sh'
          - '!docs/**'
          - '!img/**'
          - '!notebooks/**'
          - '!python/**'
          - '!readme_pages/**'
          - '!container-builder/**'
          - '!helm-chart/**'
          - '!ngc/**'
          - '!omniverse/**'
          - '!regression/**'
          - '!resources/**'
          - '!ucf/**'
          - '!utilities/**'
        test_notebooks:
          - '**'
          - '!CONTRIBUTING.md'
          - '!README.md'
          - '!ci/release/update-version-cuopt.sh'
          - '!ci/release/update-version-rapids.sh'
          - '!docs/**'
          - '!python/nvcf_client/**'
        test_python:
          - '**'
          - '!CONTRIBUTING.md'
          - '!README.md'
          - '!ci/release/update-version-cuopt.sh'
          - '!ci/release/update-version-rapids.sh'
          - '!docs/**'
          - '!img/**'
          - '!notebooks/**'
          - '!python/nvcf_client/**'
        test_python_cuopt:
          - '**'
          - '!CONTRIBUTING.md'
          - '!README.md'
          - '!ci/release/update-version-cuopt.sh'
          - '!ci/release/update-version-rapids.sh'
          - '!docs/**'
          - '!img/**'
          - '!notebooks/**'
          - '!python/cuopt_self_hosted/**'
          - '!python/cuopt_server/**'
          - '!python/nvcf_client/**'
        test_python_cuopt_server:
          - '**'
          - '!CONTRIBUTING.md'
          - '!README.md'
          - '!ci/release/update-version-cuopt.sh'
          - '!ci/release/update-version-rapids.sh'
          - '!docs/**'
          - '!img/**'
          - '!notebooks/**'
          - '!python/cuopt_self_hosted/**'
          - '!python/nvcf_client/**'
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@branch-25.08
    with:
      enable_check_generated_files: false

  conda-cpp-build:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-build.yaml@branch-25.08
    with:
      build_type: pull-request
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
      script: ci/build_cpp.sh
  conda-cpp-tests:
    needs: [conda-cpp-build, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-tests.yaml@branch-25.08
    #if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_cpp
    with:
      build_type: pull-request
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
      script: ci/test_cpp.sh
  conda-python-build:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@branch-25.08
    with:
      build_type: pull-request
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
      script: ci/build_python.sh
  conda-python-tests:
    needs: [conda-python-build, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@branch-25.08
    #if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python
    with:
      run_codecov: false
      build_type: pull-request
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
      script: ci/test_python.sh
  docs-build:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-25.08
    with:
      build_type: pull-request
      node_type: "gpu-l4-latest-1"
      arch: "amd64" 
      file_to_upload: "/tmp/cuopt_docs.zip"
      container_image: "rapidsai/ci-conda:25.08-latest"
      script: "ci/build_docs.sh"
  #conda-notebook-tests:
  #  needs: [conda-python-build, changed-files]
  #  secrets: inherit
  #  uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-25.08
  #  #if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_notebooks
  #  with:
  #    build_type: pull-request
  #    node_type: "gpu-l4-latest-1"
  #    arch: "amd64"
  #    container_image: "rapidsai/ci-conda:cuda11.8.0-ubuntu22.04-py3.10"
  #    run_script: "ci/test_notebooks.sh"
  wheel-build-cuopt-mps-parser:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-25.08
    with:
      build_type: pull-request
      script: ci/build_wheel_cuopt_mps_parser.sh
      package-name: cuopt_mps_parser
      package-type: python
      append-cuda-suffix: false
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
  wheel-build-libcuopt:
    needs: wheel-build-cuopt-mps-parser
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-25.08
    with:
      # build for every combination of arch and CUDA version, but only for the latest Python
      matrix_filter: map(select((.CUDA_VER | startswith("12")) and .PY_VER == "3.12"))
      package-type: cpp
      package-name: libcuopt
      build_type: pull-request
      script: ci/build_wheel_libcuopt.sh
  wheel-build-cuopt:
    needs: [wheel-build-cuopt-mps-parser, wheel-build-libcuopt]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-25.08
    with:
      build_type: pull-request
      script: ci/build_wheel_cuopt.sh
      package-name: cuopt
      package-type: python
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
  wheel-tests-cuopt:
    needs: [wheel-build-cuopt, wheel-build-cuopt-mps-parser, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-25.08
    #if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python_cuopt
    with:
      build_type: pull-request
      script: ci/test_wheel_cuopt.sh
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
  wheel-build-cuopt-server:
    needs: wheel-build-cuopt
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-25.08
    with:
      build_type: pull-request
      script: ci/build_wheel_cuopt_server.sh
      package-name: cuopt_server
      package-type: python
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
  wheel-build-cuopt-sh-client:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-25.08
    with:
      build_type: pull-request
      script: ci/build_wheel_cuopt_sh_client.sh
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
      package-name: cuopt_sh_client
      package-type: python
      append-cuda-suffix: false
  wheel-tests-cuopt-server:
    needs: [wheel-build-cuopt-server, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-25.08
    #if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python_cuopt_server
    with:
      build_type: pull-request
      script: ci/test_wheel_cuopt_server.sh
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
  test-self-hosted-server:
    needs: [wheel-build-cuopt-server, changed-files]
    secrets: inherit
    uses: ./.github/workflows/self_hosted_service_test.yaml
    #if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python
    with:
      build_type: pull-request
      script: ci/test_self_hosted_service.sh
